### ISSUE TITLE
crash on pff.rkt

### ISSUE THREAD

**Issue by samth** [samth/pycket#154]
` python ~/sw/pycket/targetpycket.py pff.rkt elephant.trace opt 0` produces an error for me currently, with HEAD.

**Comment by samth** [comment]
The failure is calling the `call` method of `W_StructMutator`.

```
running elephant.trace.time.0 opt
ERROR:
expected root-struct as argument 0 to <struct-mutator-method>, got 0
  while executing: (call-with-values (lambda () (run-all-ops )) print-values)
  in module: pff
Traceback (most recent call last):
  File "/home/samth/sw/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 17, in entry_point
    return actual_entry(argv)
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 41, in actual_entry
    val = interpret_module(ast, env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1845, in interpret_module
    m.interpret_mod(env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 404, in interpret_mod
    return self._interpret_mod(env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 427, in _interpret_mod
    vs = interpret_one(f, self.env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1822, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1794, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/samth/sw/pycket/pycket/cont.py", line 210, in interpret
    return func(*args)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 191, in func_arg_unwrap
    raise SchemeException(type_errormsg + arg.tostring())
SchemeException: expected root-struct as argument 0 to <struct-mutator-method>, got 0
> /home/samth/sw/pycket/pycket/prims/expose.py(191)func_arg_unwrap()
-> raise SchemeException(type_errormsg + arg.tostring())
```

**Comment by sabauma** [comment]
Probably worth mentioning that this is not a recent development. I did not think too much of this at the time, since we were not using the `opt` vartiant for benchmarking. I don't think Pycket ever successfully ran this using `opt`. Oddly, I get a slightly different error message

```
expected root-struct as argument 0 to <method>, got 0
  while executing: (call-with-values (lambda () (run-all-ops )) print-values)
  in module: pff
```
which does not mention a struct mutator.

**Comment by samth** [comment]
That's because I changed the name so I could tell what it was.

**Comment by vkirilichev** [comment]
@samth that may mean that one of primitives has wrong implementation and returns blank (0 in this case) value instead of a struct.

**Comment by krono** [comment]
@vkirilichev do you have a little time to fix that?

**Comment by vkirilichev** [comment]
@krono @samth I think yes, but I cannot reproduce the error.
Is that the right repo for these benchmarks: https://github.com/stamourv/contract-benchmarks ?

**Comment by krono** [comment]
no, should be these: https://github.com/sabauma/pycket-benchmarks

**Comment by vkirilichev** [comment]
@krono thank! ok, now I see the error

**Comment by vkirilichev** [comment]
It looks like a mutator of a structure type 'node/lazy-opt-contract' is called with arguments: 0, 0, #f, where the first argument should be a structure.

**Comment by krono** [comment]
so probably another primitive is returning `0` where it should return a structure?

**Comment by vkirilichev** [comment]
it can be true. But I cannot find the place where this mutator is called

**Comment by samth** [comment]
@vkirilichev the `node/lazy-opt-contract` comes from the contracts on `node`s (which are in "binomial-heap-contract.rkt") with the `#:lazy` keyword.

**Comment by vkirilichev** [comment]
@samth thank you.
I'm a bit confusing with this error, I found out that commenting out of line 27 in "binomial-heap.rkt" (`(define tt (hd ts))`) removes the wrong mutator call, but I don't understand why, because it is just an accessor.

**Comment by samth** [comment]
I bet that it's a lazy contract on `ts`, which saves the value of the `hd` field in a mutable struct field.

**Comment by vkirilichev** [comment]
here is the smaller example with this bug:

```
#lang racket/base
(require racket/contract)

(define-contract-struct x (a b))
(define-contract-struct y (c d))

(define-opt/c (x/opt/c)
  (x/dc [a (y/dc)]
        [b (a) (y-c a)])) ; <-

(define x-a/c (contract (-> (x/opt/c) (x/opt/c)) x-a 'pos 'neg))

(x-a/c (make-x (make-y 11 22) 33))
```

**Comment by samth** [comment]
This program has a (perhaps related) bug:

```
#lang racket/base
(require racket/contract)

(define-contract-struct x (a b))
(define-contract-struct y (c d))

(define-opt/c (x/opt/c)
  (x/dc [a (y/dc)]
        [b (a) any/c])) ; <-

(define x-a/c (contract (-> (x/opt/c) any/c) x-a 'pos 'neg))

(x-a/c (make-x (make-y 11 22) 33))
```

**Comment by samth** [comment]
Here's a simplified version of the original bug:
```
#lang racket/base
(require racket/contract)

(define-contract-struct y (c d))

(define-opt/c (yopt) (y/dc))

(y-c (contract (yopt) (make-y 1 1) 'pos 'neg))
```

**Comment by samth** [comment]
@cfbolz this bug disappears when environment pruning is turned off.

@vkirilichev The program in my previous comment (with both x and y) has a different struct-related bug -- something is going wrong with the field offsets. Can you investigate that?

**Comment by vkirilichev** [comment]
@samth ok

**Comment by vkirilichev** [comment]
@samth I think it can be the same bug, because it crashes in the structure mutator, where the argument `type` is the wrong stucture type (`x/lazy-opt-contract` is the type argument by accessing a field inside `y/lazy-opt-contract`that has no super-types). The original bug happens when instead of the structure type a number is sent.

**Comment by samth** [comment]
@vkirilichev does it go away as well (or change into the regular Racket error) when environment pruning is off?

**Comment by samth** [comment]
@vkirilichev both bugs go away with `prune_env` off, so they're almost certainly the same bug. No need to worry about this more.

**Comment by samth** [comment]
Here's a probably, related problem:

```
#lang racket/base

;; directed graph constructor
(define (f es)
  ;; Set up edges
  (define adj 0)
  (for ([e es])
    (list adj e))
  (define (in-neighbors v) adj)
  0)
```

**Comment by samth** [comment]
And even simpler:

```
(module prune-bug '#%kernel
  (#%module-begin
   (let-values (((es) values))
     (let-values (((adj) '0))
       (let-values ((() (es)))
         adj)))))
```

**Comment by sabauma** [comment]
Similarly, a little alteration causes this program to lookup the wrong values in
the environment:

```
(module prune-bug '#%kernel
  (#%module-begin
   (let-values (((es) '0))
     (let-values (((adj) '1))
       (let-values (((a b c) (begin es (values '2 '3 '4))))
         (printf "~s~n" (+ adj a)))))))
```
