### ISSUE TITLE
ODE Benchmark Error

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#156]
Looks like we may have introduced some bugs. The ODE benchmarks do not run under Pycket:
```
can't find module #%foreign for '_int8
  while executing: _int8
  in module: unsafe
```

**Comment by samth** [comment]
This looks like a change in racket to me.

**Comment by krono** [comment]
I saw this error as early as December or January iirc.
It define natively came with a Racket upgrade to (then) 6.1.1.6

-- 
Tobias Pape
sent from a mobile device

**Comment by samth** [comment]
What exact command line (preferably for pycket, not rebench) produces this error?

**Comment by sabauma** [comment]
@samth You can see this error by running `pycket-c ode.rkt` without any additional arguments.

**Comment by sabauma** [comment]
This seems to have been a case of dated JSON files.

**Comment by sabauma** [comment]
@krono If this is still an issue for you, let me know and I will reopen, but please try nuking your JSON files first.

**Comment by krono** [comment]
It's ok, just wanted to report that I encounered that a while ago
