### ISSUE TITLE
Add regexp-max-lookbehind

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#161]
Needed for some gradual typing benchmarks
See http://docs.racket-lang.org/reference/regexp.html#%28def._%28%28quote._~23~25kernel%29._regexp-max-lookbehind%29%29

**Comment by sabauma** [comment]
And several of the `regexp-match-positions`

**Comment by krono** [comment]
is the same as #135

**Comment by sabauma** [comment]
Since this is a duplicate
