### ISSUE TITLE
Poor performance with very large for-loop bodies on linux

### ISSUE THREAD

**Issue by magnusmorton** [samth/pycket#162]
If I run [this program]  (https://gist.github.com/magnusmorton/54b9400eeba9c44feefa) using racket on ubuntu it takes 0.27 seconds; If I run it on the same machine using pycket, it takes 67.63 seconds (with 49 of those seconds being 'sys' time according to ```time``` vs 0.02s when using racket). On my slower OS X machine, it takes 0.7 seconds using pycket (with 0.03s in 'sys') and 0.32 using racket.

I've tried it with the expanded version of the macro, and the results are similar.

**Comment by samth** [comment]
@magnusmorton Was it expanding the standard library during all that time? On my linux machine, I get the same results you see on OS X.

**Comment by magnusmorton** [comment]
@samth Haha, yes that's it. It wasn't saving the expanded standard lib files because I wasn't using ```sudo```... maybe I'll reinstall racket in a user-writeable location
