### ISSUE TITLE
Improve performance of hash-set

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#164]
Pycket is several order of magnitude slower for this operation. Racket probably does something much more fancy for its immutable hash tables.

Example:
```
#lang racket/base
(define d (make-immutable-hasheq '()))
(time
  (void
    (let loop ([i 0] [a d])
      (if (= i 100000) a
        (begin
          (loop (+ i 1) (hash-set a i i)))))))
```

**Comment by cfbolz** [comment]
Right now we even get the complexity wrong. Since we always copy, in pycket this code is quadratic, as opposed to n log n or something. 

Fixing this will be annoying though, don't think anybody implemented immutable data structures in rpython yet.

Carl Friedrich

**Comment by samth** [comment]
Right now, Racket uses AVL-trees keyed on the hash code. It's switching soon to using HAMTs. We won't have acceptable performance until we do something similar.

**Comment by cfbolz** [comment]
If we want to go down that road we should try to see whether we can reuse this port of clojure's persistent dict here:

https://github.com/alex/optimizer-model/blob/master/optimizer/utils/persistent_dict.py

Not rpython, but probably fairly close. And it has tests! 

Carl Friedrich

**Comment by heyLu** [comment]
[Pixie](https://github.com/pixie-lang/pixie) is also rpython based and has implementations of persistent vectors, [(hash) maps](https://github.com/pixie-lang/pixie/blob/master/pixie/vm/persistent_hash_map.py) and sets. Maybe these could be useful here, too?

**Comment by sabauma** [comment]
I've adapted the Pixie's HAMT implementation to work with Pycket. eq-/eqv-hashes are fully supported. equal-hashes will require some cleverness to get working, but we can easily support anything that does not need to call back into the evaluator.
