### ISSUE TITLE
extending pycket with new primitives

### ISSUE THREAD

**Issue by PatrickMaier** [samth/pycket#172]
I'd like to extend pycket with a minimal library for TCP networking, based on the RPython socket library.

Below is a first cut of the primitives (implemented as a dummy wrapper around Racket's TCP lib) I'd like to expose.  Question is, how I can actually expose these primitives so that the expansion step does not fail, claiming they are undefined?

<pre>
#lang racket/base

(require (prefix-in lib: racket/tcp))
(provide
  tcp-listener? tcp-listen tcp-close
  tcp-socket? tcp-accept tcp-connect tcp-setsockopt! tcp-sendall tcp-recv)

(define (tcp-listener? x)
  (lib:tcp-listener? x))

(define (tcp-listen port backlog)
  (with-handlers ([exn:fail:network? (lambda (exn) #f)])
    (lib:tcp-listen port backlog)))

(define (tcp-close listener-or-socket)
  (define x listener-or-socket)
  (cond
    [(tcp-listener? x) (lib:tcp-close x)]
    [else              (close-input-port (car x)) (close-output-port (cdr x))]))

(define (tcp-socket? x)
  (and (pair? x)
       (lib:tcp-port? (car x)) (input-port? (car x))
       (lib:tcp-port? (cdr x)) (output-port? (cdr x))))

(define (tcp-accept listener)
  (define-values (in out) (lib:tcp-accept listener))
  (cons in out))

(define (tcp-connect host port)
  (with-handlers ([exn:fail:network? (lambda (exn) #f)])
    (define-values (in out) (lib:tcp-connect host port))
    (cons in out)))

;; XXX: Can't be implemented on top of Racket's TCP lib.
(define (tcp-setsockopt! socket level option value)
  (void))

(define (tcp-sendall socket bstr)
  (write-bytes bstr (cdr socket))
  (flush-output (cdr socket)))

(define (tcp-recv socket max_bytes)
  (read-bytes max_bytes (car socket)))
  ;; XXX: Should use `read-bytes-avail!` instead of `read-bytes`.
</pre>

**Comment by samth** [comment]
You should do the following:

1. Write a racket library that exposes the necessary primitives. It doesn't have to actually do the work, just provide the right names.
2. Add a conditional in the module lookup code (the place that currently handles `#%kernel` etc) and check for your new module.
3. Then add primitives with the appropriate names.

**Comment by PatrickMaier** [comment]
Sam, could you point to the "module lookup code" more precisely? Being no Racket expert, I find the expand module rather impenetrable.

**Comment by samth** [comment]
I mean this code: https://github.com/samth/pycket/blob/master/pycket/interpreter.py#L1054

You should just need to have your module treated as a builtin module in this list: https://github.com/samth/pycket/blob/master/pycket/interpreter.py#L20

**Comment by PatrickMaier** [comment]
Just to document this. You also need to import any new prims modules to make them available to the interpreter by adding the imports here: https://github.com/samth/pycket/blob/master/pycket/prims/general.py#L23

I consider this issue closed.
