### ISSUE TITLE
Program transformations do not respect continuation mark structure

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#178]
Consider the following program

```racket
#lang racket/base

(with-continuation-mark 'hello 'bye
  (let ([x (call-with-immediate-continuation-mark 'hello (λ (x) x) #f)])
    x))
```

When we run this program

```
spenser@Mentat: ~/src/pycket
17:17:20 $ racket test.rkt
#f
spenser@Mentat: ~/src/pycket
17:18:52 $ pycket-c test.rkt
'bye
```

we see that Racket and Pycket give different answers. This appears to be due to our ANF conversion trying to be too clever. The code that gets run through the interpreter actually looks like this

```racket
(with-continuation-mark 'hello 'bye
  (call-with-immediate-continuation-mark 'hello (lambda (x3707) x3707) #f))
```

This simple transformation removes the intermediate `let`-binding, thus removing an intermediate continuation and altering the mark set flowing into `call-with-immediate-continuation-mark`.

A simple fix is to just stop doing that transform, but it seems silly that such a simple transform is not correct.

**Comment by samth** [comment]
That transform isn't correct, though, for other reasons. Consider:

```
(let ([x (values 1 2)]) x)
```

That will error in Racket, but runs in Pycket. Racket will simplify `let` bindings in some cases, but not in general. I think we should just never do it.
