### ISSUE TITLE
Module name contains ".json" suffix when directly running JSON

### ISSUE THREAD

**Issue by vishesh** [samth/pycket#184]
When we run json file directly, the module_name set by `option_helper.py:ensure_json_ast` is the original file name and hence contain ".json" file extension. This is however a problem when we use a value defined in that module as source field points to module without json extension.

Given Pycket allows to run JSON files directly, I consider this a bug. I've a small patch this [https://github.com/vishesh/pycket/commit/e34cf8c1bd2b69bd33a44e06da0a2463cdbfd6c6]

**Comment by sabauma** [comment]
The patch looks good to me. I'll accept if you make a pull request.

**Comment by vishesh** [comment]
Thanks. I've created a pull request

**Comment by krono** [comment]
OK from here
