### ISSUE TITLE
Segmentation Fault in mbta t-graph.rkt

### ISSUE THREAD

**Issue by rjnw** [samth/pycket#198]
Modified t-graph
https://gist.github.com/rjnw/d96e6fb4967bc5ad54d9e0668b1c7861

**Comment by sabauma** [comment]
I am unable to reproduce this bug after updating the equal-hash branch to include the latest changes to our mutable equal-hashes. Its likely the changes I made fixed the error. Likely something to do with iteration over hash tables.
